name: mattermonad
version: 0.1.0.0
github: iasoon/mattermonad
license: BSD3
author: Ilion Beyst
maintainer: ilion.beyst@gmail.com
copyright: 2020 Ilion Beyst
extra-source-files:
  - README.md
description: >-
  Please see the README on GitHub at
  <https://github.com/iasoon/mattermonad#readme>
dependencies:
  - base >= 4.7 && < 5
  - unordered-containers
  - aeson >= 1.4
  - http-client
  - http-types
  - http-client-tls
  - text
  - bytestring
  - case-insensitive
  - transformers
  - mtl
  - template-haskell
  - websockets
  - wuss
  - yaml
  - reflex >= 0.7
  - lens
  - hashable
default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - RecordWildCards
  - LambdaCase
library:
  source-dirs: src
executables:
  bot-monad-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - mattermonad
tests:
  bot-monad-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - mattermonad
